---
name: 'Bump Version'
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.ref }}
      - name: 'Automated Version Bump'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: version-bump
        uses: 'phips28/gh-action-bump-version@v11.0.4'
        with:
          patch-wording: 'ci,doc,patch,fixes'
          tag-prefix: 'v'
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
