---
name: CI
# yamllint disable-line rule:truthy
on:
  push:
    # the 'v*' tag means this implicitly runs after the bump.yml
    tags:
      - "v*"
  pull_request:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - denverton
          - geminilake
    runs-on: ubuntu-22.04
    env:
      SUFFIX: build-${{ matrix.arch }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Build
        run: date > ${{ env.SUFFIX }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SUFFIX }}
          path: ${{ env.SUFFIX }}
          if-no-files-found: error
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    environment: release
    needs: [linux]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Automatic Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            build-denverton
            build-geminilake
        id: 'automatic_releases'
